from typing import Literal

# https://iss.moex.com/iss/index.json?iss.only=engines
Engine = Literal[
    "stock",
    "state",
    "currency",
    "futures",
    "commodity",
    "interventions",
    "offboard",
    "agro",
    "otc",
    "quotes",
    "money",
]

# https://iss.moex.com/iss/index.json?iss.only=markets
Market = Literal[
    "repo",
    "deposit",
    "otcindices",
    "index",
    "shares",
    "bonds",
    "ndm",
    "otc",
    "ccp",
    "qnv",
    "mamc",
    "foreignshares",
    "foreignndm",
    "moexboard",
    "gcc",
    "credit",
    "selt",
    "futures",
    "main",
    "forts",
    "options",
    "fortsiqs",
    "optionsiqs",
    "sharesndm",
    "nonresndm",
    "nonresrepo",
    "nonresccp",
    "grain",
    "sugar",
    "auctions",
    "buyauctions",
    "saleauctions",
    "standard",
    "classica",
]
